name: Publish to npm

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: ['main']

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo + install pnpm
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install Packages
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Publish Package
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Slack - Build Success
        if: success()
        uses: act10ns/slack@v2.0.0
        with:
          status: ${{ job.status }}
          channel: '#alerts-deploys'
          message: 'Groudon was successfully published to npm'

      - name: Slack - Build Failed
        if: failure()
        uses: act10ns/slack@v2.0.0
        with:
          status: ${{ job.status }}
          channel: '#alerts-deploys'
          message: 'Groudon has failed to publish to npm'
